### ISSUE TITLE
work with external software like opensees

### ISSUE THREAD

**Issue by ebrahimraeyat** [robbievanleeuwen/feastruct#1]
Hello. it is very interesting project and i follow that. but my question is:
why you don't use software like [opensees](http://opensees.berkeley.edu/) for analysing?
I want to create a gui for that. thanks

**Comment by robbievanleeuwen** [comment]
Hi Ebrahim,

I had a few goals when starting this project:
- Develop my own finite element package for my own education
- Make it an open source package so that anyone can use it and import it into their own projects (including me!)
- Develop not only a frame analysis program, but also membranes, shells and bricks etc.

While OpenSees does achieve the second goal, it obviously doesn't fulfil the other goals - hence *feastruct*!

If you have any suggestions for the project I'd be happy to hear and try implementing them!

Robbie
